service: aws-python # NOTE: update this with your service name

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-python-requirements

package:
  individually: false
  exclude:
    - '**/*'
  include:
    - api.py

functions:
  hello:
    handler: api.lambda_handler
    name: drug-interaction
    events: # All events associated with this function
      - http: 'GET /'
      - http: 'POST /'