name: 'Rxchat'

on:
  push:
    branches: [ "satya" ]
#   pull_request:

# permissions:
#   contents: read

jobs:
  rxchat:
    name: 'rxchat deployment'
    runs-on: ubuntu-latest
    environment: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Copy a folder to s3
      uses: prewk/s3-cp-action@v2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        source: './webpages'
        dest: 's3://rxchat.com'
        flags: --recursive
    - name: setup python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
    - name: Use Node.js '19.x'
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'
    - run: npm ci
    - name: Install Plugin and Deploy
      uses: serverless/github-action@master
      with:
        args: -c "serverless plugin install --name serverless-python-requirements && serverless deploy"
        entrypoint: /bin/sh
    